{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "axon-cassandra.fullname" . }}
  labels:
    {{- include "axon-cassandra.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
spec:
  {{- if .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "axon-cassandra.selectorLabels" . | nindent 6 }}
      {{- with .Values.serviceMonitor.selector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  endpoints:
  - port: {{ .Values.serviceMonitor.port | default "jmx" }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.serviceMonitor.path }}
    path: {{ .Values.serviceMonitor.path }}
    {{- end }}
    {{- if .Values.serviceMonitor.scheme }}
    scheme: {{ .Values.serviceMonitor.scheme }}
    {{- end }}
    {{- if .Values.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml .Values.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml .Values.serviceMonitor.relabelings | nindent 6 }}
    {{- end }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 6 }}
    {{- end }}
  {{- if .Values.serviceMonitor.targetLabels }}
  targetLabels:
    {{- toYaml .Values.serviceMonitor.targetLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml .Values.serviceMonitor.podTargetLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.sampleLimit }}
  sampleLimit: {{ .Values.serviceMonitor.sampleLimit }}
  {{- end }}
{{- end }}