{{- if and .Values.backups.enabled (eq .Values.backups.target.type "local") }}
{{- if not .Values.backups.target.local.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opensearch.uname" . }}-backup
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.backups.target.local.storageClass }}
  {{- if eq .Values.backups.target.local.storageClass "-" }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.backups.target.local.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backups.target.local.size | default "10Gi" }}
{{- end }}
{{- end }}
