{{- if and (eq .Values.backups.target.type "s3") .Values.backups.target.s3.credentials.accessKeyId .Values.backups.target.s3.credentials.secretAccessKey (not .Values.backups.target.s3.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensearch.uname" . }}-s3-credentials
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
type: Opaque
data:
  aws-access-key-id: {{ .Values.backups.target.s3.credentials.accessKeyId | b64enc }}
  aws-secret-access-key: {{ .Values.backups.target.s3.credentials.secretAccessKey | b64enc }}
  {{- if .Values.backups.target.s3.credentials.sessionToken }}
  aws-session-token: {{ .Values.backups.target.s3.credentials.sessionToken | b64enc }}
  {{- end }}
{{- end }}
