{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.basicAuth.enabled (not .Values.serviceMonitor.basicAuth.existingSecret) (not .Values.vals.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opensearch.uname" . }}-service-monitor-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  username: {{ .Values.serviceMonitor.basicAuth.username | b64enc | quote }}
  password: {{ .Values.serviceMonitor.basicAuth.password | b64enc | quote }}
{{- end }}
