{{- if .Values.vals.enabled }}
{{- /*
  ValsSecret resource for vals-operator integration.
  vals-operator will reconcile this into a standard Kubernetes Secret
  by resolving the ref+ expressions from external secret stores.

  Reference: https://github.com/digitalis-io/vals-operator
*/ -}}
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: {{ include "opensearch.uname" . }}-vals
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
    {{- with .Values.vals.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.vals.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  name: {{ include "opensearch.uname" . }}-vals
  ttl: {{ .Values.vals.ttl | default 3600 }}
  data:
    {{- if .Values.vals.authentication.opensearch_user }}
    AXONOPS_SEARCH_USER:
      ref: {{ .Values.vals.authentication.opensearch_user | quote }}
    {{- end }}
    {{- if .Values.vals.authentication.opensearch_password }}
    AXONOPS_SEARCH_PASSWORD:
      ref: {{ .Values.vals.authentication.opensearch_password | quote }}
    {{- end }}
    {{- if .Values.vals.tls.keystorePassword }}
    KEYSTORE_PASSWORD:
      ref: {{ .Values.vals.tls.keystorePassword | quote }}
    {{- end }}
    {{- if .Values.vals.s3Credentials.accessKeyId }}
    AWS_ACCESS_KEY_ID:
      ref: {{ .Values.vals.s3Credentials.accessKeyId | quote }}
    {{- end }}
    {{- if .Values.vals.s3Credentials.secretAccessKey }}
    AWS_SECRET_ACCESS_KEY:
      ref: {{ .Values.vals.s3Credentials.secretAccessKey | quote }}
    {{- end }}
    {{- if .Values.vals.s3Credentials.sessionToken }}
    AWS_SESSION_TOKEN:
      ref: {{ .Values.vals.s3Credentials.sessionToken | quote }}
    {{- end }}
    {{- if .Values.vals.serviceMonitor.username }}
    SERVICE_MONITOR_USERNAME:
      ref: {{ .Values.vals.serviceMonitor.username | quote }}
    {{- end }}
    {{- if .Values.vals.serviceMonitor.password }}
    SERVICE_MONITOR_PASSWORD:
      ref: {{ .Values.vals.serviceMonitor.password | quote }}
    {{- end }}
{{- end }}
