repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: .*.md
      - id: end-of-file-fixer
        exclude: .*.md
      - id: check-yaml
        exclude: ^axonops/charts/.*
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
        exclude: ^(axonops/charts/.*|\.github/workflows/.*)
