apiVersion: v2
name: axon-server
description: Install AxonOps server - Unified observability platform for Apache Cassandra
home: https://axonops.com
icon: https://static.wixstatic.com/media/a5611a_ade5ecd5de154e5381d2e13067f1aec3~mv2.png/v1/fill/w_163,h_47,al_c,usm_1.20_1.00_0.01,enc_auto/tr_logo.png
keywords:
  - cassandra
  - monitoring
  - observability
  - metrics
  - alerting
  - kafka
maintainers:
  - name: AxonOps Team
    email: info@axonops.com
    url: https://axonops.com

sources:
  - https://github.com/axonops/axonops-containers

type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.0

# This is the version number of the application being deployed.
appVersion: "latest"

kubeVersion: ">=1.19.0-0"
