---
apiVersion: v1
kind: Secret
metadata:
  name: axonops-agent
  namespace: ${KAFKA_NAMESPACE}
stringData:
  AXON_AGENT_CLUSTER_NAME: ${AXON_AGENT_CLUSTER_NAME}
  AXON_AGENT_ORG: ${AXON_AGENT_ORG}
  AXON_AGENT_SERVER_HOST: ${AXON_AGENT_SERVER_HOST}
  AXON_AGENT_KEY: ${AXON_AGENT_KEY}
