{{- if and .Values.serviceAccount.create .Values.serviceAccount.createClusterRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "axon-server.fullname" . }}
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "axon-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "axon-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}