apiVersion: v2
name: axondb-search
description: This helm chart installs the backeding search engine for AxonOps
icon: https://github.com/axonops/axonops-workbench/raw/main/renderer/assets/images/axonops-icon-512x512.png
maintainers:
  - name: AxonOps Team
    email: info@aoxnops.com
home: https://github.com/axonops/axonops-containers/
sources:
  - https://github.com/opensearch-project/opensearch
  - https://github.com/opensearch-project/helm-charts
keywords:
  - axonops
  - monitoring
  - kafka
  - cassandra
  - opensearch
  - search
  - logging

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "3.3.2-2.4.17"
