{{- if .Values.opensearchInitialAdminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opensearch.uname" . }}-admin-password
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
type: Opaque
data:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: {{ .Values.opensearchInitialAdminPassword | b64enc }}
{{- end }}