apiVersion: v1
stringData:
  AXON_AGENT_CLUSTER_NAME: kafka
  AXON_AGENT_ORG: example
  AXON_AGENT_SERVER_HOST: agents.axonops.cloud
  AXON_AGENT_KEY: CHANGEME
kind: Secret
metadata:
  name: axonops-agent
  namespace: kafka
